# Generated by Django 5.0.3 on 2024-03-13 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidebargrid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebaritem',
            name='parent_item_id',
        ),
        migrations.AddField(
            model_name='sidebaritem',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sidebargrid.sidebaritem'),
        ),
        migrations.AlterField(
            model_name='sidebaritem',
            name='is_parent_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sidebaritem',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
